steps:
  - label: ":ubuntu:"
    command: ./src/show_environment.sh
    plugins:
      - docker#v3.5.0:
          image: "ubuntu:latest"
          propagate-environment: true
  - wait
  
  - label: ":ski: missing bash"
    commands: 
      - /src/show_environment.sh
     
    plugins:
      - docker#v3.5.0:
          image: "alpine:latest"
          propagate-environment: true
